services:
  - type: web
    name: study-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /login
    envVars:
      - key: APP_NAME
        value: Study App
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_LOCALE
        value: ja
      - key: APP_FALLBACK_LOCALE
        value: ja
      - key: APP_FAKER_LOCALE
        value: ja_JP
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: study-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: study-app-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: study-app-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: study-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: study-app-db
          property: password

databases:
  - name: study-app-db
    plan: free
